name: Aling E Commerce Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📂 Pulling files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEMO_SSH_HOST }}
          username: ${{ secrets.DEMO_SSH_USERNAME }}
          key: ${{ secrets.DEMO_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DEMO_SSH_PORT }}
          script: |
            PROJECT_DIR=~/1.0.0

            mkdir -p $PROJECT_DIR
            cd $PROJECT_DIR

            if [ -d ".git" ]; then
              echo "Repository exists, pulling latest changes..."
              git reset --hard origin/main
              git pull origin main
            else
              echo "Repository does not exist, cloning..."
              git clone git@github.com:faidfadjri/aling.git .
            fi
            composer install
            npm install
            npm run build
